### ISSUE TITLE
Metadata not found for lots of variables

### ISSUE THREAD

**Issue by t-davidson** [fragilefamilieschallenge/metadata_api#11]
I'm getting a lot of errors when I try to query the API using Python. It appears that a lot of variables are not included. Most are `hv` variables but there are some others. Is there an explanation for this missingness, e.g. the metadata for one segment has not yet been digitized? See the full list of missing variables I found below.

Also note that it may be possible that some of these names are erroneous, but I have tried to check careful to make sure they are real variables. 

Thanks!

```
hv4d1e
hv4r10a_8
hv4c13
hv3u1
hv4b2
hv5_haz
hv3e8
hv3pvbasal
hv5_dsraw
hv4g23i
hv3m21
hv4u7
hv4l42
hv3f5
hv4b23
hv4r13
hv4a10
hv3m40a
f2fb1
cm2md_case
hv4g16
hv4g23n
hv3pvpercom_m
hv4g3
hv5_dsae
hv4b24
hv3b4_hr
hv3k2b
hv4ppvtage
hv3j3
hv3j23a
hv3a6b
hv5_ppvtss
hv3g1h
hv4k5_expen
hv4a30
hv4l45
hv4e4
hv4b6
hv4c1e
hv4s1_9
cm5md_case
hv4r10a_3
hv3c_c3
hv4f2b1
hv4f3b
hv5_dsss
hv4l47
hv3b1a
hv4f3e
hv3g1a
hv3pvbasal_m
hv4f2a1
hv4wjraw22
hv4g19
hv4c2
hv3e2
hv4p8
hv4a14
hv3a6a
hv3r10a6
hv3s1_7
hv3accdt
hv4f1i
hv4pvtwceil
hv5_wj10raw
hv3m18b
hv3k1a
hv3g1k
hv4a22
hv4l39
hv3b5
hv4s1_6
hv4a4
hv4b4
hv4g23b
hv3h2b
f2fh18
hv4d15f
hv4a11
cf4md_case
hv3u2
hv4l23
hv4g1
hv3j23b
hv3l6
hv4a8
hv4k8
hv4g17
hv3c6d
hv3m7a
hv3k1b
hv4u2
hv3m45
hv3m29
hv4f1a
hv4b16
hv4l16
hv3b1
m4d7
hv4p10
m1lenhr
f2fb33
hv4l11
hv4g12
hv4l17
hv3b7_6
hv3h3d
hv3l1
hv3j10
hv4pvceil
hv3m3
hv4g24b
hv4g13
hv3b14
hv3j23j
```

**Comment by t-davidson** [comment]
p.s. Feel free to move this if this is not the correct place for it. I found a couple of different repos relevant to the metadata project and this seemed the most appropriate one to make the issue in.

**Comment by msalganik** [comment]
Thanks for the bug report @t-davidson.  We've recently changed the names of some of the variable names in order to standardize things going forward and not all the variables in the Challenge file are in the regular Fragile Families file.  One thing to try would be using the "old_name" field and/or the "new_name" field.

Beyond that, I think @thartshorne can perhaps answer this.  @thartshorne please note that @t-davidson is probably using the names in v1 of the Challenge file.

**Comment by t-davidson** [comment]
I'll try to use the `old_name` field to find them. If possible it would be really useful to have a dictionary mapping the old names to the new names.

**Comment by msalganik** [comment]
thanks @t-davidson.  Also, I'm looping in @shivarouhani.  She's knows all about the variable names and how they changed.  I think one tricky thing is that the challenge variable name might not be either the new_name or old_name.  @shivarouhani what do you think about the variables that @t-davidson found?

**Comment by t-davidson** [comment]
Yes, that seems to be the case. I tried to get the new name for the variables that were failing but I can't find a `new_name` for the vast majority, 106/116 of them. I can get metadata for all but 3 of these from Connor Gilroy's [csv file](https://github.com/fragilefamilieschallenge/variables-metadata).

**Comment by shivarouhani** [comment]
hi @t-davidson! this is, indeed, tricky! this problem has to do with slightly different naming conventions used in the challenge file vs original fragile families files! first, the vast majority of the variables you've listed are part of the in-home assessments from waves 3 and 4 (the variables you list that are NOT from the in-home survey are: m1lenhr, f2fb33, cf4md_case, f2fb21, f2fh18, cm2md_case and m4d7 which may account for why you were able to find metadata for seven of them!).  in the challenge files, in-home variables were listed with a prefix hv3 or hv4. in the fragile families data the in-home variables were downloadable from the site WITHOUT a prefix. to merge these files onto the master file, we suggested using ih3 or ih4 as the prefix as to avoid having duplicate in-home variable names. resulting from this suggestion is that the "old_name" in-home variables have a different prefix in the fragile families files than those of the challenge files! furthermore, the names for the in-home variables have been updated. 
the in-home variables that were once ih[3|4][a-n] are now p[3|4][a-n].  "p" as prefix to reflect that these variables belong to the parental caregiver interview, ih[3|4][p-v] is now o[3|4][p-v] (this is so because these variables are the interviewer's observations of the home) -- everything other than these specific in-home sections are in-home activities (like the ppvt test) and those variables are are now named ch[3|4]..

**Comment by t-davidson** [comment]
Thanks @shivarouhani, I tried to convert your response into a function and it seems to work for almost all but 4 cases: hv4k5_expen, hv3c_c3, hv3r10a6, hv3accdt. 

The function is a bit hacky (regular expressions would probably be a better way to do it) but the new names work in the metadata API. 

```
import string

def convertToNew(var):
    """Takes an old variable name from the in house survey and converts it to a new one."""
    chars = [x for x in string.ascii_lowercase]
    if not var.startswith('hv'):
        print("This variable does not start with hv")
        return
    else:
        var = var[2:] # Remove hv prefix
        if var[1] in chars[:14]: #if [a-n]
            return 'p'+var
        elif var[1] in chars[14:22]: #if [p-v]
            if var[2] in chars: # if next element is another character
                return 'ch'+var 
            else: # if not assign o prefix
                return 'o'+var
```

I should be good for now but will let you know if I run into any other issues.

**Comment by t-davidson** [comment]
@shivarouhani thanks for getting the other names. I don't have any problems with closing the issue but it would be great to somehow integrate this functionality into the API, i.e. have different versions of variable names all map to the current name.

**Comment by vineetbansal** [comment]
This issue was moved to fragilefamilieschallenge/metadata_app#57
