### ISSUE TITLE
move from Pyhton 2.X to Python 3.X

### ISSUE THREAD

**Issue by msalganik** [fragilefamilieschallenge/metadata_api#18]

**Comment by vineetbansal** [comment]
This would ideally be done after the server (current or target server) is provisioned to use both Python 2.x and 3.x. I'd need a day for this migration, but this would ideally happen when no other developers are working on the codebase, so the entire existing codebase gets migrated and merged on the trunk.

**Comment by vineetbansal** [comment]
I've restructured the code to follow the usual pattern of enclosing functionality in a top level module ('ffmeta') with submodules inside it. If @atkindel and @thartshorne can take a look at the 'Python3' branch of the code and give their okay, we can (perhaps the same time as officially migrating the server), merge these changes to the trunk.

I've tested this out on Python 3.6, with Flask 1.0 (and the packages listed in requirements.txt) and everything seems good so far.

A few notable changes:
- I'm using Flask blueprints to provide web-accessible routes. This will make it easy to break down the routes into logical units in the future without the risk of ending up with a huge single file of code.
- I'm using plain SqlAlchemy here instead of Flask-SqlAlchemy. This is partly because Flask-SqlAlchemy binds the concepts of the Flask Application object and the Database connection object, preventing these from being used independently (unless one creates application contexts etc. which can get confusing). The only practical ways in which this affects future Python code is that instead of saying:

   `Umbrella.query.filter(...)`

  we would say:

  `from ffmeta.models.db import session`
  `session.query(Umbrella).filter(...)`

A few items with my recommendations:

- All csv files (current and future) should go inside a 'data' folder inside the ffmeta package, and access to these be made available using calls to functions (not yet written) in the ffmeta module, not directly. It's fine to write unit-tests to check these csv files directly, but I'd recommend no code be written (outside ffmeta) that access the data folder at all.
- I've deleted files that are redundant with this refactoring to avoid clutter.
- I'm not quite sure what localMetaData.py does, so I've left it as is. Perhaps it can go inside the ffmeta package in some way too.

**Comment by msalganik** [comment]
@atkindel and @thartshorne it would great if you could have your approval or any questions to @vineetbansal by the end of the day Wednesday.  That would give him Thursday and Friday morning to migrate and then we can send this to the board.  Also, if you don't have any questions that's fine too.  Thanks.
cc @katejaeger

**Comment by msalganik** [comment]
@thartshorne and @atkindel I'd like to give @vineetbansal the chance to move ahead with the Python 3 branch.  So unless we hear from you by Friday at the end of the day, @vineetbansal will go ahead and start with the Python 3 branch on Monday.  

I realize that you might not want to review the code, and that's fine too.  But I wanted to give you the chance. cc @katejaeger

**Comment by vineetbansal** [comment]
I've sent a merge request for the python3 branch
